[deps]
PatternVectors = "92638b5e-77be-42fd-8598-99573a47aaa0"
BenchmarkTools = "6e4b80f9-dd63-53aa-95a3-0cdb28fa8baf"
DataFrames = "a93c6f00-e57d-5684-b7b6-d8193f3e46c0"
Franklin = "713c75ef-9fc9-4b05-94a9-213340da978e"
NodeJS = "2bd173c7-0d6d-553b-b6af-13a54713934c"
PkgPage = "e7214860-93a8-4f22-b43d-bd447d1a2094"

[compat]
BenchmarkTools = "1"
DataFrames = "1"
Franklin = "0.10"
NodeJS = "1, 2"
PkgPage = "0.4"
